// Mocks generated by Mockito 5.4.4 from annotations
// in dream_catcher/test/features/dream/domain/use-cases/interview/get_current_interview_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dream_catcher/core/error/failure.dart' as _i5;
import 'package:dream_catcher/features/dream/domain/entities/dream_interview.dart'
    as _i6;
import 'package:dream_catcher/features/dream/domain/repositories/dream_interview_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DreamInterviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDreamInterviewRepository extends _i1.Mock
    implements _i3.DreamInterviewRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DreamInterview>> startInterview() =>
      (super.noSuchMethod(
        Invocation.method(
          #startInterview,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.DreamInterview>>.value(
                _FakeEither_0<_i5.Failure, _i6.DreamInterview>(
          this,
          Invocation.method(
            #startInterview,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.DreamInterview>>.value(
                _FakeEither_0<_i5.Failure, _i6.DreamInterview>(
          this,
          Invocation.method(
            #startInterview,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.DreamInterview>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DreamInterview>> addMessage(
    String? interviewId,
    _i6.SpeakerType? speakerType,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMessage,
          [
            interviewId,
            speakerType,
            content,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.DreamInterview>>.value(
                _FakeEither_0<_i5.Failure, _i6.DreamInterview>(
          this,
          Invocation.method(
            #addMessage,
            [
              interviewId,
              speakerType,
              content,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.DreamInterview>>.value(
                _FakeEither_0<_i5.Failure, _i6.DreamInterview>(
          this,
          Invocation.method(
            #addMessage,
            [
              interviewId,
              speakerType,
              content,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.DreamInterview>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> getBotResponse(
    String? interviewId,
    List<_i6.DreamInterviewMessage>? previousMessages,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBotResponse,
          [
            interviewId,
            previousMessages,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #getBotResponse,
            [
              interviewId,
              previousMessages,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #getBotResponse,
            [
              interviewId,
              previousMessages,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> completeInterview(
          String? interviewId) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeInterview,
          [interviewId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #completeInterview,
            [interviewId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #completeInterview,
            [interviewId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> convertVoiceToText(
          List<int>? audioData) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertVoiceToText,
          [audioData],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #convertVoiceToText,
            [audioData],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #convertVoiceToText,
            [audioData],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DreamInterview>> getCurrentInterview(
          String? interviewId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentInterview,
          [interviewId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.DreamInterview>>.value(
                _FakeEither_0<_i5.Failure, _i6.DreamInterview>(
          this,
          Invocation.method(
            #getCurrentInterview,
            [interviewId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.DreamInterview>>.value(
                _FakeEither_0<_i5.Failure, _i6.DreamInterview>(
          this,
          Invocation.method(
            #getCurrentInterview,
            [interviewId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.DreamInterview>>);
}
