// Mocks generated by Mockito 5.4.4 from annotations
// in dream_catcher/test/features/dream/presentation/bloc/dream_interview_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:dream_catcher/core/error/failure.dart' as _i6;
import 'package:dream_catcher/features/dream/domain/entities/dream_interview.dart'
    as _i7;
import 'package:dream_catcher/features/dream/domain/repositories/dream_interview_repository.dart'
    as _i2;
import 'package:dream_catcher/features/dream/domain/use-cases/interview/add_message.dart'
    as _i8;
import 'package:dream_catcher/features/dream/domain/use-cases/interview/complete_interview.dart'
    as _i9;
import 'package:dream_catcher/features/dream/domain/use-cases/interview/convert_voice_to_text.dart'
    as _i10;
import 'package:dream_catcher/features/dream/domain/use-cases/interview/get_current_interview.dart'
    as _i11;
import 'package:dream_catcher/features/dream/domain/use-cases/interview/start_interview.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDreamInterviewRepository_0 extends _i1.SmartFake
    implements _i2.DreamInterviewRepository {
  _FakeDreamInterviewRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StartInterview].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartInterview extends _i1.Mock implements _i4.StartInterview {
  @override
  _i2.DreamInterviewRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDreamInterviewRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDreamInterviewRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.DreamInterviewRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.DreamInterview>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.DreamInterview>>.value(
                _FakeEither_1<_i6.Failure, _i7.DreamInterview>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.DreamInterview>>.value(
                _FakeEither_1<_i6.Failure, _i7.DreamInterview>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.DreamInterview>>);
}

/// A class which mocks [AddMessage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddMessage extends _i1.Mock implements _i8.AddMessage {
  @override
  _i2.DreamInterviewRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDreamInterviewRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDreamInterviewRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.DreamInterviewRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.DreamInterview>> call(
          _i8.AddMessageParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.DreamInterview>>.value(
                _FakeEither_1<_i6.Failure, _i7.DreamInterview>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.DreamInterview>>.value(
                _FakeEither_1<_i6.Failure, _i7.DreamInterview>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.DreamInterview>>);
}

/// A class which mocks [CompleteInterview].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompleteInterview extends _i1.Mock implements _i9.CompleteInterview {
  @override
  _i2.DreamInterviewRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDreamInterviewRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDreamInterviewRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.DreamInterviewRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>> call(
          _i9.CompleteInterviewParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>.value(
            _FakeEither_1<_i6.Failure, _i3.Unit>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>.value(
                _FakeEither_1<_i6.Failure, _i3.Unit>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>);
}

/// A class which mocks [ConvertVoiceToText].
///
/// See the documentation for Mockito's code generation for more information.
class MockConvertVoiceToText extends _i1.Mock
    implements _i10.ConvertVoiceToText {
  @override
  _i2.DreamInterviewRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDreamInterviewRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDreamInterviewRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.DreamInterviewRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> call(
          _i10.AudioDataParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, String>>.value(
                _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [GetCurrentInterview].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentInterview extends _i1.Mock
    implements _i11.GetCurrentInterview {
  @override
  _i2.DreamInterviewRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDreamInterviewRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDreamInterviewRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.DreamInterviewRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.DreamInterview>> call(
          _i11.InterviewIdParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.DreamInterview>>.value(
                _FakeEither_1<_i6.Failure, _i7.DreamInterview>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.DreamInterview>>.value(
                _FakeEither_1<_i6.Failure, _i7.DreamInterview>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.DreamInterview>>);
}
